model:
    learning_rate: 0.02
    policy_output_size: 4672 # For 8x8x73 stack
    value_output_size: 3

mcts:
    max_nodes: 300
    thinking_time: 500

train:
    num_epochs: 10000
    num_self_play_games: 25
    num_simulations: 1
    max_depth: 15
    batch_size: 8
    replay_buffer_size: 5000
    evaluation_interval: 10   # Evaluate every 10 iterations
    save_model: true
    model_checkpoint_dir: "checkpoints/"
    training_steps: 250

evaluation:
    num_simulations: 10
    max_depth: 10
    num_games: 5
pretrain:
    batch_size: 64
    num_epochs: 1000
    validation_batch_size: 1024
    validation_interval: 10
    evaluation_interval: 100

visualize: true
verbose: false
