model:
    learning_rate: 0.05
    policy_output_size: 4672 # For 8x8x73 stack
    value_output_size: 3

mcts:
    max_nodes: 3600
    thinking_time: 10

train:
    num_epochs: 200
    num_self_play_games: 100
    batch_size: 32
    num_simulations: 100
    replay_buffer_size: 30000
    evaluation_interval: 5   # Evaluate every 10 iterations
    save_model: true
    model_checkpoint_dir: "checkpoints/"
    training_steps: 250

evaluation:
    num_simulations: 800
    max_depth: 10
    num_games: 5
pretrain:
    batch_size: 128
    num_epochs: 10
    validation_batch_size: 100
    validation_interval: 1
    alpha: 0.9

visualize: true
verbose: false
